package com.cj.mcbaseball.team;

import java.util.Random;

public final class NameGenerator {
    private static final String[] FIRST = new String[]{
        "Jake",
        "Marcus",
        "Eli",
        "Diego",
        "Tyler",
        "Sam",
        "Owen",
        "Luis",
        "Caleb",
        "Andre",
        "Miles",
        "Noah",
        "Hector",
        "Ryan",
        "Dylan",
        "Mateo",
        "Jordan",
        "Cole",
        "Isaac",
        "Trevor",
        "Gabe",
        "Victor",
        "Nate",
        "Leo",
        "Bryce",
        "Kenji",
        "Omar",
        "Felix",
        "Grant",
        "Wes",
        "Ty",
        "Rafael",
        "Dante",
        "Colby",
        "Evan",
        "Joel",
        "Shawn",
        "Theo",
        "Ramon",
        "Kyle",
        "Jalen",
        "Hugo",
        "Brady",
        "Ivan",
        "Reed",
        "Tomas",
        "Darius",
        "Max"
    };
    private static final String[] LAST = new String[]{
        "Carter",
        "Reyes",
        "Holloway",
        "Brooks",
        "Nakamura",
        "Delgado",
        "Whitfield",
        "Morrison",
        "Patel",
        "Ortega",
        "Fischer",
        "Hayes",
        "Kowalski",
        "Bennett",
        "Santos",
        "McAllister",
        "Ramirez",
        "Lindqvist",
        "Dawson",
        "Okafor",
        "Sullivan",
        "Navarro",
        "Pierce",
        "Takeda",
        "Gallagher",
        "Vasquez",
        "Bishop",
        "Rourke",
        "Castillo",
        "Weaver",
        "Ferraro",
        "Lockhart",
        "Mendez",
        "Harper",
        "Quinn",
        "Abernathy",
        "Torres",
        "Kline",
        "Valdez",
        "Sterling",
        "Booker",
        "Moreau",
        "Jensen",
        "Calloway",
        "Ibarra",
        "Wolfe",
        "Sato",
        "Prescott"
    };

    public static String random(Random r) {
        return FIRST[r.nextInt(FIRST.length)] + " " + LAST[r.nextInt(LAST.length)];
    }

    private NameGenerator() {
    }
}
